#ifndef APP_CONFIG_H
#define APP_CONFIG_H

#define APP_BUSY_TASK_TEST_ENABLE 0

#define APP_MONITOR_TASK_ENABLE 0
#define APP_MONITOR_TASK_PERIOD_MS 5000U

#define APP_LOG_ENABLE 1
#define APP_LOG_QUEUE_DEPTH 8
#define APP_LOG_MODULE_NAME_MAX_LEN 32
#define APP_LOG_MESSAGE_MAX_LEN 256

#define APP_INPUT_ENABLE 1
#define APP_INPUT_DEBUG_TASK_ENABLE 1
#define APP_INPUT_EVENT_QUEUE_DEPTH 8
#define APP_INPUT_SCAN_PERIOD_MS 10U
#define APP_INPUT_DEBOUNCE_MS 30U
#define APP_INPUT_LONG_PRESS_MS 300U

#endif /* APP_CONFIG_H */
